<div class="row">

	<div class="col-md-3">
		<div class="panel-group" id="accordion">
			<?php foreach($this->params["cities"] as $key => $value):?>
				<div class="panel panel-default">
					<div class="panel-heading">
						<h4 class="panel-title">
							<a data-toggle="collapse" data-parent="#accordion" href="#collapse<?php echo $key;?>">
								<?php echo $value["oblast"]?>
							</a>
						</h4>
					</div>
					<div id="collapse<?php echo $key;?>" class="panel-collapse collapse">
						<div class="panel-body">
							<ul class = "cities-list">
								<?php foreach($value["city"] as $cities):?>
									<li>
										<a href = "/city/<?php echo $cities["city"]?>"><?php echo $cities["city"]?></a>
									</li>
								<?php endforeach;?>
							</ul>
						</div>
					</div>
				</div>
			<?php endforeach;?>
		</div>
	</div>

	<div class="col-md-9">

		<div class="row">

			<?php $c = 0;$r = 0;?>
			<?php foreach($this->params["terrorists"] as $key =>  $terrorist):?>

				<?php if(!($r % 3)):?><div class="row"><?php endif;?>

				<?php if($c == 4 || $c == 10 || $c == 16):?>
					<div class="col-md-4 portfolio-item">
						<?php echo $this->ads();?>
					</div>
				<?php else:?>
					<div class="col-sm-4 col-lg-4 col-md-4">
						<div class="thumbnail">
							<a href="/member/<?php echo $terrorist["id"]?>" class = "picture-holder">
								<img class = "img-responsive" alt = "<?php echo "{$terrorist["last_name"]} {$terrorist["first_name"]}"?>" src="/data/img/vata/crop_small_<?php echo $terrorist["img"]["img_name"]?>" alt="">
							</a>
							<div class="caption">
								<h4>
									<a href="/member/<?php echo $terrorist["id"]?>"><?php echo "{$terrorist["last_name"]} {$terrorist["first_name"]}"?></a>
								</h4>
								<p>See more snippets like this online store item at <a target="_blank" href="http://www.bootsnipp.com">Bootsnipp - http://bootsnipp.com</a>.</p>
							</div>
							<div class="ratings">
								<p class="pull-right">15 reviews</p>
								<p>
									<span class="glyphicon glyphicon-star"></span>
									<span class="glyphicon glyphicon-star"></span>
									<span class="glyphicon glyphicon-star"></span>
									<span class="glyphicon glyphicon-star"></span>
									<span class="glyphicon glyphicon-star"></span>
								</p>
							</div>
						</div>
					</div>
				<?php endif;?>
				<?php $c++;$r++?>

				<?php if(!($r % 3)):?></div><?php endif;?>

			<?php endforeach;?>

		</div>

	</div>

</div>