<?php $imgFolder = (APPLICATION_ENV == "testing") ? "/data/img/vata/" : "http://vataclub.s3.amazonaws.com/"?>
<div class="row">
	<div class="col-lg-12">
		<h1 class="page-header"><?php echo  "{$this->params["terrorist"]["last_name"]} {$this->params["terrorist"]["first_name"]}"?></h1>
		<p>Додав:
			<a target = "_blank" href = "<?php echo $this->profile($this->params["publisher"]["social"])?><?php echo $this->params["publisher"]["facebook_id"]?>"><?php echo $this->params["publisher"]["first_name"]?> <?php echo $this->params["publisher"]["last_name"]?></a>
		</p>
		<form role="form" method = "POST" action = "/album/edit/<?php echo $this->params["terrorist"]["id"]?>" enctype="multipart/form-data">
			<input type = "hidden" name = "owner_id" value = "<?php echo $this->params["terrorist"]["owner_id"]?>">
			<div class="form-group">
				<input type="text" class="form-control" id="TerrorFirstName" placeholder="<?php echo $this->translate("Ім'я")?>" name = "first_name" value = "<?php echo $this->params["terrorist"]["first_name"]?>">
			</div>
			<div class="form-group">
				<input type="text" class="form-control" id="TerrorLastName" placeholder="<?php echo $this->translate("Прізвище")?>" name = "last_name" value = "<?php echo $this->params["terrorist"]["last_name"]?>">
			</div>
			<div class="form-group">
				<input type="text" class="form-control" id="TerrorBirthdate" placeholder="Рік народження" name = "birthdate" value = "<?php echo $this->params["terrorist"]["birthdate"]?>">
			</div>
			<div class="form-group">
				<input type="text" class="form-control" id="TerrorVk" placeholder="Сторінка в VK" name = "vk" value = "<?php echo $this->params["terrorist"]["vk"]?>">
			</div>
			<div class="form-group">
				<input type="text" class="form-control" id="TerrorFb" placeholder="Сторінка Facebook" name = "fb" value = "<?php echo $this->params["terrorist"]["fb"]?>">
			</div>
			<div class="form-group">
				<input type="text" class="form-control" id="TerrorTwitter" placeholder="Сторінка Twitter" name = "tw" value = "<?php echo $this->params["terrorist"]["tw"]?>">
			</div>
			<div class="form-group">
				<input type="text" class="form-control" id="TerrorVidoe" placeholder="Відео" name = "video" value = "<?php echo $this->params["terrorist"]["video"]?>">
			</div>
			<div class="form-group">
				<select class="form-control" id="TerrorObl" name = "oblast">
					<?php foreach($this->params["oblast"] as $value):?>
						<option value = "<?php echo $value["id"]?>" <?php if($this->params["terrorist"]["oblId"] == $value["id"]) echo "selected"?>><?php echo $this->translate($value["oblast"])?></option>
					<?php endforeach;?>
				</select>
			</div>
			<div class="form-group">
				<select class="form-control" id="TerrorCity" name = "city">
					<?php foreach($this->params["city"] as $value):?>
						<?php if($this->params["terrorist"]["cityId"] == $value["id"]):?>
							<option value = "<?php echo $value["id"]?>" selected><?php echo $this->translate($value["city"])?></option>
						<?php endif;?>
					<?php endforeach;?>
				</select>
			</div>
			<div class="form-group">
				<select class="form-control" id="TerrorStatus" name = "type">
					<option value = ""><?php echo $this->translate("Тип")?></option>
					<option value = "Жертва Кісєльова (виліковна)"><?php echo $this->translate("Жертва Кісєльова (виліковна)")?></option>
					<option value = "Жертва Кісєльова (невиліковна)"><?php echo $this->translate("Жертва Кісєльова (невиліковна)")?></option>
					<option value = "Ярий путіносос"><?php echo $this->translate("Ярий путіносос")?></option>
					<option value = "Лугандонєц"><?php echo $this->translate("Лугандонєц")?></option>
					<option value = "Сепаратюжка"><?php echo $this->translate("Сепаратюжка")?></option>
					<option value = "Террорист - воєватник"><?php echo $this->translate("Террорист - воєватник")?></option>
				</select>
			</div>
			<div class="form-group">
				<select class="form-control" id="TerrorStatus" name = "status">
					<option value = ""><?php echo $this->translate("Статус")?></option>
					<option value = "Пропагує сепаратизм"><?php echo $this->translate("Пропагує сепаратизм")?></option
					<option value = "Намагається стати добривом"><?php echo $this->translate("Намагається стати добривом")?></option>
					<option value = "Шліфує в пеклі обєголовки дидив з НКВД"><?php echo $this->translate("Шліфує в пеклі обєголовки дидив з НКВД")?></option>
				</select>
			</div>
			<div class="form-group">
				<textarea name = "description" cols = "120" rows = "10" id ="TerrorDescription" name = "TerrorDescription" placeholder = "Додаткова інформація"><?php echo $this->params["terrorist"]["description"]?></textarea>
			</div>
			<div class="form-group">
				<label for="exampleInputFile">Завантаження фото</label>
				<input type="file" id="exampleInputFile" name = "photos[]" multiple>
			</div>
			<div class = "clearfix"></div>
			<button type="submit" class="btn btn-success">Зберегти</button>
		</form>
	</div>
</div>
<div class="row">
	<div class="col-md-12">
		<h3>Фото</h3>
	</div>
</div>
<?php $r = 0;?>
<?php foreach($this->params["images"] as $key => $value):?>

	<?php if(!($r % 4)):?><div class="row"><?php endif;?>

		<div class="col-sm-3 col-lg-3 col-md-3">
			<div class = "img-holder">
				<i data-id = "<?php echo $value["id"]?>" class="fa fa-trash-o drop-terror-img"></i>
				<input type = "radio" name = "is_main" value = "<?php echo $value["id"]?>" class = "is_main" <?php if($value["is_main"] == 1) echo "checked"?>>
				<a class="fancybox" href="<?php echo $imgFolder.$value["img_name"]?>" data-fancybox-group="gallery">
					<img class="grouped_elements img-thumbnail" rel="group1" src="<?php echo $imgFolder.$value["img_name"]?>">
				</a>
			</div>
		</div>
	<?php $r++?>

	<?php if(!($r % 4)):?></div><?php endif;?>

<?php endforeach;?>

<div class="modal fade" id="cropImg" tabindex="-1" role="dialog" aria-labelledby="cropImgLabel" aria-hidden="true">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
				<h4 class="modal-title" id="cropImgLabel"><?php echo $this->translate("Обробка зображення")?></h4>
			</div>
			<div class="modal-body text-center">
				<div><img id = "cropSrc" src = ""></div>
				<form action="crop.php" method="post">
					<input type="hidden" name="x1" value="" />
					<input type="hidden" name="y1" value="" />
					<input type="hidden" name="x2" value="" />
					<input type="hidden" name="y2" value="" />
					<button class = "btn btn-success cropIt">CROP</button>
				</form>
			</div>
		</div>
	</div>
</div>

