<div class="row">
	<div class="col-lg-7">
		<h1 class="page-header">
			<?php $targetUpdate = isset($this->params["identity"]->id) ? "myEdit" : "myModal"; ?>
			<?php $targetDelete = isset($this->params["identity"]->id) ? "myDelete" : "myModal"; ?>
			<?php echo $this->translate("")?><?php echo "{$this->params["terrorist"]["last_name"]} {$this->params["terrorist"]["first_name"]}"?>
			<i class="fa fa-edit propose-update" data-toggle="modal" data-target="#<?php echo $targetUpdate;?>"></i>
			<i class="fa fa-trash-o propose-delete" data-toggle="modal" data-target="#<?php echo $targetDelete;?>"></i>
		</h1>
	</div>
	<div class="col-lg-5">
		<!-- Go to www.addthis.com/dashboard to customize your tools -->
		<div class="addthis_sharing_toolbox"></div>
		<!-- Go to www.addthis.com/dashboard to customize your tools -->
		<script type="text/javascript" src="//s7.addthis.com/js/300/addthis_widget.js#pubid=ra-53ff4f4d4343c2b3"></script>
	</div>
</div>
<div class="row">
	<div class="col-lg-7">
		<div class="table-responsive">
			<table class="table table-bordered">
				<tr>
					<td><?php echo $this->translate("Ім'я")?></td>
					<td><?php echo "{$this->params["terrorist"]["last_name"]} {$this->params["terrorist"]["first_name"]}"?></td>
				</tr>
				<tr>
					<td><?php echo $this->translate("Дата народження")?></td>
					<td><?php echo $this->params["terrorist"]["birthdate"]?></td>
				</tr>
				<tr>
					<td><?php echo $this->translate("Область");?></td>
					<td><?php echo $this->params["terrorist"]["oblname"]?></td>
				</tr>
				<tr>
					<td><?php echo $this->translate("Місто");?></td>
					<td><?php echo $this->params["terrorist"]["cityname"]?></td>
				</tr>
				<tr>
					<td>Vkontakte</td>
					<td><a class = "adlink" target = "_blank" href = "<?php echo trim($this->params["terrorist"]["vk"])?>"><?php echo $this->params["terrorist"]["vk"]?></a></td>
				</tr>
				<tr>
					<td>Facebook</td>
					<td><a class = "adlink" href = "<?php echo trim($this->params["terrorist"]["fb"])?>"><?php echo $this->params["terrorist"]["fb"]?></a></td>
				</tr>
				<tr>
					<td>Twitter</td>
					<td><a class = "adlink" href = "<?php echo trim($this->params["terrorist"]["tw"])?>"><?php echo $this->params["terrorist"]["tw"]?></a></td>
				</tr>
				<tr>
					<td>OK</td>
					<td><a class = "adlink" href = "<?php echo trim($this->params["terrorist"]["ok"])?>"><?php echo $this->params["terrorist"]["ok"]?></a></td>
				</tr>
				<tr>
					<td><?php echo $this->translate("Тип")?></td>
					<td><?php echo $this->translate($this->params["terrorist"]["type"])?></td>
				</tr>
				<tr>
					<td><strong><?php echo $this->translate("Статус")?></strong></td>
					<td><strong><?php echo $this->translate($this->params["terrorist"]["status"])?></strong></td>
				</tr>
				<tr>
					<td><?php echo $this->translate("Додаткова інформація")?></td>
					<td>
						<?php
						if ($this->translate($this->params["terrorist"]["id"] < 730)){
							echo nl2br($this->translate($this->params["terrorist"]["description"]));
						}else{
							echo $this->translate($this->params["terrorist"]["description"]);
						}
						?>
					</td>
				</tr>
				<tr>
					<td><?php echo $this->translate("Підтримати проект")?></td>
					<td>
						<form class = "webmoney-form" action="https://advisor.wmtransfer.com/Spasibo.aspx" method="post" target="_blank" title="Передать $пасибо! нашему сайту">
							<input type="hidden" name="url" value="http://vata.club"/>
							<input type="image" src="//advisor.wmtransfer.com/img/Spasibo!.png" border="0" name="submit"/>
						</form>
						<iframe frameborder="0" allowtransparency="true" scrolling="no" src="https://money.yandex.ru/embed/small.xml?account=410011036444901&quickpay=small&yamoney-payment-type=on&button-text=06&button-size=s&button-color=orange&targets=%D0%9F%D0%BE%D0%B4%D0%B4%D0%B0%D1%80%D0%B6%D0%BA%D0%B0+%D0%B4%D0%BB%D1%8F+%D0%BF%D1%80%D0%BE%D0%B5%D0%BA%D1%82%D0%B0+%D0%BF%D0%BE%D0%B8%D1%81%D0%BA%D0%B0+%D0%BF%D1%80%D0%BE%D0%BF%D0%B0%D0%B2%D1%88%D0%B8%D1%85%D0%B2+%D0%A3%D0%BA%D1%80%D0%B0%D0%B8%D0%BD%D0%B5+%D1%80%D1%83%D1%81%D1%81%D0%BA%D0%B8%D1%85+%D1%81%D0%BE%D0%BB%D0%B4%D0%B0%D1%82&default-sum=100&mail=on&successURL=" width="146" height="31"></iframe>
					</td>
				</tr>
			</table>
			<?php $this->ads();?>
		</div>
	</div>
	<div class="col-lg-5">
		<?php if(isset($this->params["images"][0]["img_name"])):?>

			<?php if(isset($this->params["closed"])):?>
				<p style = "color:red"><?php echo $this->translate("Для перегляду фото 18+ необхідна авторизація")?></p>
			<?php endif;?>

			<div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
				<!-- Indicators -->
				<ol class="carousel-indicators">
					<li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
					<li data-target="#carousel-example-generic" data-slide-to="1"></li>
					<li data-target="#carousel-example-generic" data-slide-to="2"></li>
				</ol>

				<!-- Wrapper for slides -->
				<div class="carousel-inner">
					<div class="item active">
						<a class="fancybox" href="http://vataclub.s3.amazonaws.com/<?php echo $this->params["images"][0]["img_name"]?>" data-fancybox-group="gallery" title="<?php echo "{$this->params["terrorist"]["last_name"]} {$this->params["terrorist"]["first_name"]}"?>">
							<img class="grouped_elements" rel="group1" src="http://vataclub.s3.amazonaws.com/<?php echo $this->params["images"][0]["img_name"]?>" alt="<?php echo "{$this->params["terrorist"]["last_name"]} {$this->params["terrorist"]["first_name"]}"?>">
						</a>
						<div class="carousel-caption">
							<?php echo "{$this->params["terrorist"]["last_name"]} {$this->params["terrorist"]["first_name"]}"?>
						</div>

					</div>
					<?php foreach($this->params["images"] as $key => $value):?>
						<?php if($key != 0):?>
						<div class="item">
							<a class="fancybox" href="http://vataclub.s3.amazonaws.com/<?php echo $value["img_name"]?>" data-fancybox-group="gallery" title="<?php echo "{$this->params["terrorist"]["last_name"]} {$this->params["terrorist"]["first_name"]}"?>">
								<img class="grouped_elements" rel="group1" src="http://vataclub.s3.amazonaws.com/<?php echo $value["img_name"]?>" alt="...">
							</a>
							<div class="carousel-caption">
								<?php echo "{$this->params["terrorist"]["last_name"]} {$this->params["terrorist"]["first_name"]}"?>
							</div>
						</div>
						<?php endif;?>
					<?php endforeach;?>

				</div>

				<!-- Controls -->
				<a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
					<span class="glyphicon glyphicon-chevron-left"></span>
				</a>
				<a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
					<span class="glyphicon glyphicon-chevron-right"></span>
				</a>
			</div>
		<?php endif;?>
		<?php if(isset($this->params["terrorist"]["video"])):?>
			<h4><?php echo $this->translate("Відео")?> </h4>
			<iframe src="<?php echo $this->params["terrorist"]["video"]?>"  frameborder="0" allowfullscreen></iframe>
		<?php endif;?>
	</div>
</div>

<div class="modal fade" id="myDelete" tabindex="-1" role="dialog" aria-labelledby="myDelete" aria-hidden="true">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
				<h4 class="modal-title" id="myEditLabel"><?php echo $this->translate("Я хочу видалити")?> <?php echo $this->translate("з vata.club")?></h4>
			</div>
			<div class="modal-body">
				<div class="row subscribe-form">
					<div class="col-lg-12">
						<form role="form" method = "POST" action = "/album/propose" enctype="multipart/form-data">
							<div class="form-group">
								<input value = "<?php echo $this->params["identity"]->first_name . " " . $this->params["identity"]->last_name?>" type="text" class="form-control" id="proposerName" name = "name" disabled>
							</div>
							<div class="form-group">
								<?php $disabled = (!empty($this->params["identity"]->email)) ? "disabled" : "" ?>
								<input value = "<?php echo $this->params["identity"]->email ?>" type="text" class="form-control" id="proposerEmail" placeholder="<?php echo $this->translate("E-mail")?>" name = "email" <?php echo $disabled?>>
							</div>
							<div class="form-group">
								<textarea name = "reason" cols = "60" rows = "5" id = "proposerReason" placeholder = "<?php echo $this->translate("Причина для видалення")?>"></textarea>
							</div>
							<button type="submit" class="btn btn-success send-propose"><?php echo $this->translate("Надіслати")?></button>
						</form>
					</div>
				</div>
			</div>
			<div class="modal-footer">
			</div>
		</div>
	</div>
</div>

<div class="modal fade" id="myEdit" tabindex="-1" role="dialog" aria-labelledby="myEditLabel" aria-hidden="true">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
				<h4 class="modal-title" id="myEditLabel"><?php echo $this->translate("Підпишіться на наші новини")?></h4>
			</div>
			<div class="modal-body">
				<div class="row subscribe-form">
					<div class="col-lg-12">
						<form role="form" method = "POST" action = "/album/propose" enctype="multipart/form-data">
							<div class="form-group">
								<input value = "<?php echo $this->params["terrorist"]["name"]?>" type="text" class="form-control" id="TerrorFirstName" placeholder="<?php echo $this->translate("Ім'я")?>" name = "name">
							</div>
							<div class="form-group">
								<input value = "<?php echo $this->params["terrorist"]["birthdate"]?>" type="text" class="form-control" id="TerrorFirstName" placeholder="<?php echo $this->translate("Дата народження")?>" name = "birthdate">
							</div>
							<div class="form-group">
								<input value = "<?php echo $this->params["terrorist"]["city"]?>"  type="text" class="form-control" id="TerrorCity" placeholder="<?php echo $this->translate("Місто")?>" name = "city">
							</div>
							<div class="form-group">
								<input value = "<?php echo $this->params["terrorist"]["vk"]?>"  type="text" class="form-control" id="TerrorVk" placeholder="<?php echo $this->translate("Сторінка в VK")?>" name = "vk">
							</div>
							<div class="form-group">
								<input value = "<?php echo $this->params["terrorist"]["fb"]?>"  type="text" class="form-control" id="TerrorFb" placeholder="<?php echo $this->translate("Сторінка Facebook")?>" name = "fb">
							</div>
							<div class="form-group">
								<input value = "<?php echo $this->params["terrorist"]["tw"]?>"  type="text" class="form-control" id="TerrorTwitter" placeholder="<?php echo $this->translate("Сторінка Twitter")?>" name = "tw">
							</div>
							<div class="form-group">
								<input value = "<?php echo $this->params["terrorist"]["video"]?>"  type="text" class="form-control" id="TerrorVideo" placeholder="<?php echo $this->translate("Відео")?>" name = "video">
							</div>
							<div class="form-group">
								<select class="form-control" id="TerrorStatus" name = "type">
									<option value = ""><?php echo $this->translate("Тип")?></option>
									<option value = "Найманці з Росії" <?php if($this->params["terrorist"]["type"] == "Найманці з Росії") echo "selected"?>><?php echo $this->translate("Найманці з Росії")?></option>
									<option value = "Російські військові" <?php if($this->params["terrorist"]["type"] == "Російські військові") echo "selected"?>><?php echo $this->translate("Російські військові")?></option>
								</select>
							</div>
							<div class="form-group">
								<select class="form-control" id="TerrorStatus" name = "status">
									<option value=""><?php echo $this->translate("Статус")?></option>
									<option value="Вбитий" <?php if($this->params["terrorist"]["status"] == "Вбитий") echo "selected"?>><?php echo $this->translate("Вбитий")?></option>
									<option value="Полонений" <?php if($this->params["terrorist"]["status"] == "Полонений") echo "selected"?>><?php echo $this->translate("Полонений")?></option>
									<option value="Помічений в Україні" <?php if($this->params["terrorist"]["status"] == "Помічений в Україні") echo "selected"?>><?php echo $this->translate("Помічений в Україні")?></option>
									<option value="Можливо був в Україні" <?php if($this->params["terrorist"]["status"] == "Можливо був в Україні") echo "selected"?>><?php echo $this->translate("Можливо був в Україні")?></option>
								</select>
							</div>
							<div class="form-group">
								<textarea name = "description" cols = "30" rows = "5" id ="TerrorDescription" name = "TerrorDescription" placeholder = "<?php echo $this->translate("Додаткова інформація")?>"><?php echo $this->translate($this->params["terrorist"]["description"])?></textarea>
							</div>
							<button type="submit" class="btn btn-success"><?php echo $this->translate("Додати")?></button>
						</form>
					</div>
				</div>
			</div>
			<div class="modal-footer">
			</div>
		</div>
	</div>
</div>





