<?php

$identity = Zend_Auth::getInstance()->getStorage()->read();
header('Cache-control: max-age='.(60*60*24));
header('Expires: '.gmdate(DATE_RFC1123,time()+60*60*24));

?>
<!DOCTYPE html>
<html lang="en">

<head>

	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta name="description" content="">
	<meta name="author" content="">

	<title>Vata.Club - Клую ватників та сепаратистів України</title>

	<!-- Bootstrap Core CSS -->
	<link href="/css/bootstrap/bootstrap.min.css" rel="stylesheet">

	<!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
	<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
	<!--[if lt IE 9]>
	<script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
	<script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
	<![endif]-->

	<?php echo $this->headTitle(); ?>
	<?php echo $this->headMeta(); ?>

</head>


<body>

<!-- Navigation -->
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
	<div class="container">
		<!-- Brand and toggle get grouped for better mobile display -->
		<div class="navbar-header">
			<button type="button" class="navbar-toggle" data-toggle="collapse"
			        data-target="#bs-example-navbar-collapse-1">
				<span class="sr-only">Toggle navigation</span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>
			<a class="navbar-brand" href="<?php echo $this->baseUrl();?>"><?php echo $this->translate("Головна") ?></a>
		</div>
		<!-- Collect the nav links, forms, and other content for toggling -->
		<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
			<ul class="nav navbar-nav">
				<?php $target = isset($identity->id) ? "addRussian" : "myModal"; ?>
				<li>
					<a data-toggle="modal" data-target="#<?php echo $target; ?>">
						<?php echo $this->translate("Додати інформацію") ?>
					</a>
				</li>
				<?php if (!isset($identity->id)): ?>
					<li>
						<a data-toggle="modal" data-target="#myModal">
							<?php echo $this->translate("Авторизація") ?>
						</a>
					</li>
				<?php endif; ?>
				<?php $target = isset($identity->id) ? "myContact" : "myModal"; ?>
				<li>
					<a data-toggle="modal" data-target="#<?php echo $target;?>">
						<?php echo $this->translate("Зворотній зв'язок") ?>
					</a>
				</li>
				<li>
					<a href="/news"><?php echo $this->translate("Новини")?></a>
				</li>
				<li>
					<a data-toggle="modal" class = "followUs" data-target="#myFollow">
						<?php echo $this->translate("Follow Us") ?>
					</a>
				</li>
				<?php if (isset($identity->role) && ($identity->role == "admin" || $identity->role == "editor")): ?>
					<li class="dropdown">
						<a href="#" class="dropdown-toggle" data-toggle="dropdown">Admin<span class="caret"></span></a>
						<ul class="dropdown-menu" role="menu">
							<?php if($identity->role == "editor" || $identity->role == "admin"):?><li><a href="/admin">Edit</a></li><?php endif;?>
							<?php if($identity->role == "editor" || $identity->role == "admin"):?><li><a href="/cms/list">News</a></li><?php endif;?>
							<?php if($identity->role == "admin"):?><li><a href="/admin/users">Users</a></li><?php endif;?>
							<?php if($identity->role == "admin"):?><li><a href="/admin/cache">Cache</a></li><?php endif;?>
						</ul>
					</li>
				<?php endif; ?>
				<?php if (isset($identity->id)) :?>
					<li>
						<a href = "/user/logout">
							<?php echo $this->translate("Вихід") ?>
						</a>
					</li>
				<?php endif; ?>

				<?php $language = $this->lang();?>

				<li class="dropdown">
					<button class="dropdown-toggle btn btn-default navbar-btn lang-btn" data-toggle="dropdown">
						<img src="/data/img/design/1px.png" class="flag flag-<?php echo $language["type"]?>" alt="<?php echo $language["name"]?>" /> <?php echo $language["name"]?>
						<span class="caret"></span>
					</button >
					<ul class="dropdown-menu" role="menu" >
						<?php if((isset($_COOKIE["language"]) && $_COOKIE["language"] != "en") || !isset($_COOKIE["language"])):?><li><a class = "lang-select" href="#" data-lang = "en" data-href = "<?php echo $_SERVER['REQUEST_URI']?>"><img src="/data/img/design/1px.png" class="flag flag-en" alt="English" /> English</a></li><?php endif;?>
						<?php if((isset($_COOKIE["language"]) && $_COOKIE["language"] != "ru") || !isset($_COOKIE["language"])):?><li><a class = "lang-select" href="#" data-lang = "ru" data-href = "<?php echo $_SERVER['REQUEST_URI']?>"><img src="/data/img/design/1px.png" class="flag flag-ru" alt="Русский" /> Русский</a></li><?php endif;?>
						<?php if((isset($_COOKIE["language"]) && $_COOKIE["language"] != "ua") || !isset($_COOKIE["language"])):?><li><a class = "lang-select" href="#" data-lang = "ua" data-href = "<?php echo $_SERVER['REQUEST_URI']?>"><img src="/data/img/design/1px.png" class="flag flag-ua" alt="Українська" /> Українська</a></li><?php endif;?>
						<?php if((isset($_COOKIE["language"]) && $_COOKIE["language"] != "pl") || !isset($_COOKIE["language"])):?><li><a class = "lang-select" href="#" data-lang = "pl" data-href = "<?php echo $_SERVER['REQUEST_URI']?>"><img src="/data/img/design/1px.png" class="flag flag-pl" alt="Polskie" /> Polskie</a></li><?php endif;?>
						<?php if((isset($_COOKIE["language"]) && $_COOKIE["language"] != "lv") || !isset($_COOKIE["language"])):?><li><a class = "lang-select" href="#" data-lang = "lv" data-href = "<?php echo $_SERVER['REQUEST_URI']?>"><img src="/data/img/design/1px.png" class="flag flag-lv" alt="Latviešu" /> Latviešu</a></li><?php endif;?>
						<?php if((isset($_COOKIE["language"]) && $_COOKIE["language"] != "lt") || !isset($_COOKIE["language"])):?><li><a class = "lang-select" href="#" data-lang = "lt" data-href = "<?php echo $_SERVER['REQUEST_URI']?>"><img src="/data/img/design/1px.png" class="flag flag-lt" alt="Latviešu" /> Lithuanian </a></li><?php endif;?>
						<?php if((isset($_COOKIE["language"]) && $_COOKIE["language"] != "ge") || !isset($_COOKIE["language"])):?><li><a class = "lang-select" href="#" data-lang = "ge" data-href = "<?php echo $_SERVER['REQUEST_URI']?>"><img src="/data/img/design/1px.png" class="flag flag-ge" alt="Deutsch" /> Deutsch</a></li><?php endif;?>
						<?php if((isset($_COOKIE["language"]) && $_COOKIE["language"] != "it") || !isset($_COOKIE["language"])):?><li><a class = "lang-select" href="#" data-lang = "it" data-href = "<?php echo $_SERVER['REQUEST_URI']?>"><img src="/data/img/design/1px.png" class="flag flag-it" alt="Italiano" /> Italiano</a></li><?php endif;?>
					</ul>
				</li>

			</ul>
		</div>
		<!-- /.navbar-collapse -->
	</div>
	<!-- /.container -->
</nav>
<!-- Page Content -->


<!-- Page Content -->
<div class="container">
	<?php echo $this->layout()->content;?>
</div>
<!-- /.container -->

<div class="container">

	<hr>

	<!-- Footer -->
	<footer>
		<div class="row">
			<div class="col-lg-12">
				<p>Copyright &copy; Your Website 2014</p>
			</div>
		</div>
	</footer>

</div>

<!-- /.container -->

<?php echo $this->partial('partials/login.phtml') ?>
<?php echo $this->partial('partials/form.phtml') ?>
<?php echo $this->partial('partials/contact.phtml') ?>
<?php echo $this->partial('partials/follow.phtml') ?>


<!-- Custom CSS -->
<link href="/css/custom/shop-homepage.css" rel="stylesheet">
<link href="/css/custom/mobile.css" rel="stylesheet">
<link href="/css/custom/style.css" rel="stylesheet">
<link href="/css/custom/flags.css" rel="stylesheet">
<link href="/css/bootstrap/font-awesome.min.css" rel="stylesheet">

<!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
<!--[if lt IE 9]>
<script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
<script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>

<![endif]-->

<!-- jQuery Version 1.11.0 -->
<script src="/js/libs/jquery/jquery-lib.js"></script>
<!--<script src="../js/libs/jquery/jquery.uploadifive.js"></script> -->
<!-- Bootstrap Core JavaScript -->
<script src="/js/libs/bootstrap/bootstrap.min.js"></script>

<?php if(isset($this->params["fancybox"])):?>

	<script type="text/javascript" src="/js/libs/fancybox/jquery.mousewheel-3.0.6.pack.js"></script>
	<script type="text/javascript" src="/js/libs/fancybox/jquery.fancybox.js?v=2.1.5"></script>
	<script type="text/javascript" src="/js/libs/fancybox/jquery.fancybox-buttons.js?v=1.0.5"></script>
	<script type="text/javascript" src="/js/libs/fancybox/jquery.fancybox-thumbs.js?v=1.0.7"></script>
	<script type="text/javascript" src="/js/libs/fancybox/jquery.fancybox-media.js?v=1.0.6"></script>

	<link rel="stylesheet" type="text/css" href="/css/fancybox/jquery.fancybox-thumbs.css?v=1.0.7" />
	<link rel="stylesheet" type="text/css" href="/css/fancybox/jquery.fancybox-buttons.css?v=1.0.5" />
	<link rel="stylesheet" type="text/css" href="/css/fancybox/jquery.fancybox.css?v=2.1.5" media="screen" />
	<script type = "text/javascript">
		$(document).ready(function () {$('.fancybox').fancybox();});
	</script>
<?php endif;?>

<?php if(isset($this->params["ckeditor"])):?>
	<script type="text/javascript" src="/js/libs/ckeditor/ckeditor.js"></script>
	<script type = "text/javascript">
		CKEDITOR.replace( 'TerrorDescription' );
	</script>
<?php endif;?>


<?php if(isset($this->params["crop"])):?>
	<script type="text/javascript" src="/js/libs/jquery/jquery.imgareaselect.pack.js"></script>
	<link href="/css/crop/imgareaselect-animated.css" rel="stylesheet">
	<script type = "text/javascript">
		$(document).ready(function () {
			$('img#cropSrc').imgAreaSelect({
				maxWidth: 270,
				maxHeight: 200,
				onSelectEnd: function (img, selection) {
					$('input[name="x1"]').val(selection.x1);
					$('input[name="y1"]').val(selection.y1);
					$('input[name="x2"]').val(selection.x2);
					$('input[name="y2"]').val(selection.y2);
				}
			})
		});
	</script>
<?php endif;?>


<script src="/js/custom.js"></script>




<?php setcookie("follow",'1',time()+604800 ,'/');?>
<script type="text/javascript" src="//s7.addthis.com/js/300/addthis_widget.js#pubid=ra-53ff4f4d4343c2b3"></script>

</body>

</html>
