<div class="row">
	<div class="col-md-12">
		<form role="form" action = "/cms/create" method = "POST" enctype="multipart/form-data">
			<div class="form-group">
				<input type="text" name = "article_name" class="form-control" id="exampleInputName" placeholder="<?php echo $this->translate("Назва")?>">
			</div>
			<div class="form-group">
				<input type="text" name = "article_description" class="form-control" id="exampleInputName" placeholder="<?php echo $this->translate("Короткий опис")?>">
			</div>
			<div class="form-group">
				<input type="text" name = "article_source" class="form-control" id="exampleInputPassword1" placeholder="<?php echo $this->translate("Джерело")?>">
			</div>
			<div class="form-group">
				<select class="form-control" id="type" name = "type">
					<option value = ""><?php echo $this->translate("Тип")?></option>
					<option value = "link"><?php echo $this->translate("Новини з інтернету")?></option>
					<option value = "mother"><?php echo $this->translate("Комітет солдатських метерів")?></option>
					<option value = "news"><?php echo $this->translate("Новини сайту")?></option>
					<option value = "ads"><?php echo $this->translate("Реклама")?></option>
				</select>
			</div>
			<div class="form-group">
				<?php echo $this->translate("Головне зображення статті")?><input type="file" id="photos" name = "photos">
			</div>
			<div class="form-group">
				<textarea cols = "30" rows = "5" id ="TerrorDescription" name = "article_text" placeholder = "<?php echo $this->translate("Додаткова інформація")?>"></textarea>
			</div>
			<button type="submit" class="btn btn-success"><?php echo $this->translate("Зберегти")?></button>
		</form>
	</div>
</div>