<div class="row">
	<div class="col-lg-12">
		<p><?php echo $this->translate("Найкраща ваша підтримка це поширення інформації серед друзів та в мережі.")?></p>
		<p><?php echo $this->translate("Якщо Ви хочете посприяти покращенню роботи наших серверів, які знаходяться під постійними DOS атаками та пришвидшити збір інформації то ось наші реквізити")?></p>
	</div>
</div>
<div class="row">
	<div class="col-lg-12">
		<div class="table-responsive">
			<table class="table table-bordered">
				<tr>
					<td>Яндекс: </td><td><iframe frameborder="0" allowtransparency="true" scrolling="no" src="https://money.yandex.ru/embed/small.xml?account=410011036444901&quickpay=small&yamoney-payment-type=on&button-text=06&button-size=s&button-color=orange&targets=%D0%9F%D0%BE%D0%B4%D0%B4%D0%B0%D1%80%D0%B6%D0%BA%D0%B0+%D0%B4%D0%BB%D1%8F+%D0%BF%D1%80%D0%BE%D0%B5%D0%BA%D1%82%D0%B0+%D0%BF%D0%BE%D0%B8%D1%81%D0%BA%D0%B0+%D0%BF%D1%80%D0%BE%D0%BF%D0%B0%D0%B2%D1%88%D0%B8%D1%85%D0%B2+%D0%A3%D0%BA%D1%80%D0%B0%D0%B8%D0%BD%D0%B5+%D1%80%D1%83%D1%81%D1%81%D0%BA%D0%B8%D1%85+%D1%81%D0%BE%D0%BB%D0%B4%D0%B0%D1%82&default-sum=100&mail=on&successURL=" width="146" height="31"></iframe></td>
				</tr>
				<tr>
					<td>Webmoney: </td>
					<td>
						<form action="https://advisor.wmtransfer.com/Spasibo.aspx" method="post"
						      target="_blank" title="Передать $пасибо! нашему сайту">
							<input type="hidden" name="url" value="http://vata.club"/>
							<input type="image" src="//advisor.wmtransfer.com/img/Spasibo!.png" border="0" name="submit"/>
						</form>
					</td>
				</tr>
				<tr>
					<td>PrivatBank</td>
					<td>
						UAH 4149625805847207<br>
						USD 4731185602602325
					</td>
				</tr>
			</table>
		</div>
	</div>
</div>