<div class="row">
	<div class="col-lg-12">
		<h1 class="page-header">Facebook</h1>
		<div class="table-responsive">
			<table class="table table-bordered list-of-albums">
				<tr>
					<td>ID</td>
					<td>Delete</td>
				</tr>
				<?php foreach($this->params["list"] as $value):?>
					<tr>
						<td>http://vata.club/member/<?php echo $value["id"]?></td>
						<td><i data-id = "<?php echo $value["id"]?>" class="fa fa-trash-o drop-facebook"></i></td>
					</tr>
				<?php endforeach;?>
			</table>
		</div>
	</div>
</div>