<?php $config = Zend_Registry::get('config');?>
<!-- Page Header -->
<div class="row">
	<div class="col-lg-12">
		<h1 class="page-header"><?php echo $this->translate("Груз 200: русские солдаты пропавшие в Украине") ?></h1>
	</div>
</div>
<!-- /.row -->

<!-- Projects Row -->
<div class="row">
	<?php foreach($this->params["terrorists"] as $terrorist):?>
	<div class="col-md-4 portfolio-item">
		<a class = "ivan-holder" href="/ivan/<?php echo $terrorist["id"]?>">
			<img class="img-responsive" src="http://<?php echo $config->amazon->bucket?>.s3.amazonaws.com/<?php echo $terrorist["img_name"]?>" alt="">
		</a>
		<h3>
			<a href="/ivan/<?php echo $terrorist["id"]?>"><?php echo $terrorist["name"]?></a>
		</h3>
		<p class = "terror_info"><?php echo $terrorist["description"]?>.</p>
	</div>
	<?php endforeach;?>
</div>
<!-- /.row -->


<hr>

<!-- Pagination -->
<!--
<div class="row text-center">
	<div class="col-lg-12">
		<ul class="pagination">
			<li>
				<a href="#">&laquo;</a>
			</li>
			<li class="active">
				<a href="#">1</a>
			</li>
			<li>
				<a href="#">2</a>
			</li>
			<li>
				<a href="#">3</a>
			</li>
			<li>
				<a href="#">4</a>
			</li>
			<li>
				<a href="#">5</a>
			</li>
			<li>
				<a href="#">&raquo;</a>
			</li>
		</ul>
	</div>
</div>
-->
<!-- /.row -->

<hr>