<div class="modal fade" id="myContact" tabindex="-1" role="dialog" aria-labelledby="myContactLabel" aria-hidden="true">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
				<h4 class="modal-title" id="myContactLabel"><?php echo $this->translate("Зворотній зв'язок")?></h4>
			</div>
			<div class="modal-body">
				<form role="form" method = "POST" action = "/?mailsend=1" enctype="multipart/form-data">
					<div class="form-group">
						<input type="text" class="form-control" id="emailName" placeholder="<?php echo $this->translate("Ім'я")?>" name = "name">
					</div>
					<div class="form-group">
						<input type="text" class="form-control" id="emailEmail" placeholder="<?php echo $this->translate("E-mail")?>" name = "email">
					</div>
					<div class="form-group">
						<input type="text" class="form-control" id="emailTheme" placeholder="<?php echo $this->translate("Тема")?>" name = "theme">
					</div>
					<div class="form-group">
						<textarea name = "description" cols = "30" rows = "5" id ="TerrorDescription" name = "TerrorDescription" placeholder = "<?php echo $this->translate("Додаткова інформація")?>"></textarea>
					</div>
					<button type="submit" class="btn btn-success"><?php echo $this->translate("Надіслати")?> </button>
				</form>
			</div>
			<div class="modal-footer">

			</div>
		</div>
	</div>
</div>