<div class="modal fade" id="myFollow" tabindex="-1" role="dialog" aria-labelledby="myFollowLabel" aria-hidden="true">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
				<h4 class="modal-title" id="myModalLabel"><?php echo $this->translate("Підпишіться на наші новини")?></h4>
			</div>
			<div class="modal-body">
				<div class="row subscribe-form">
					<div class="col-lg-12">
						<form class="navbar-form navbar-left follow-form" role="search" method = "POST" action = "/?subscribe=1">
							<div class="form-group">
								<input id="subscribe" type="text" name = "subscribe" class="form-control" placeholder="<?php echo $this->translate("Отримувати новини")?>">
							</div>
							<button type="submit" class="btn btn-default">
								<i class="fa fa-envelope-o"></i>
							</button>
						</form>
					</div>
				</div>
				<div class="row follow-form">
					<div class="col-lg-12">
						<div class="addthis_horizontal_follow_toolbox"></div>
					</div>
				</div>
			</div>
			<div class="modal-footer">
			</div>
		</div>
	</div>
</div>
<script type="text/javascript" src="//s7.addthis.com/js/300/addthis_widget.js#pubid=ra-53ff4f4d4343c2b3"></script>
