<?php

	$config = Zend_Registry::get('config');
	$google = new Application_Model_Google();
	$url    = new My_View_Helper_Url();

	$facebook = new Facebook_Facebook(array(
		'appId'  => $config->facebook->appId,
		'secret' => $config->facebook->token,
	));

	$params = array(
		'scope' => 'publish_stream,email,user_birthday',
		'redirect_uri' => "{$url->url(1)}/user/facebook/"
	);

	#$social["google"] = $google->GoogleLink();
	$social["config"] = $config;
	$social["facebook"] = $facebook->getLoginUrl( $params);

?>
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
				<h4 class="modal-title" id="myModalLabel"><?php echo $this->translate("Авторизація")?> / <?php echo $this->translate("Реєстрація")?></h4>
			</div>
			<div class="modal-body text-center">
				<button class = "login-button" data-href = "<?php echo $social["facebook"];?>" type="button" class="btn btn-default btn-lg">
					<i class="fa fa-facebook fa-2x"></i>
				</button>
				<button class = "login-button" data-href = "http://oauth.vk.com/authorize?client_id=<?php echo $social["config"]->vk->appId;?>&redirect_uri=<?php echo $social["config"]->vk->url;?>&scope=notify,friends,wall&response_type=code" type="button" class="btn btn-default btn-lg">
					<i class="fa fa-vk fa-2x"></i>
				</button>
				<!--
				<button class = "login-button" data-href = "<?php #echo $social["google"];?>" type="button" class="btn btn-default btn-lg">
					<i class="fa fa-google-plus fa-2x"></i>
				</button>
				<button class = "login-button" data-href = "/user/twitter" type="button" class="btn btn-default btn-lg">
					<i class="fa fa-twitter fa-2x"></i>
				</button>
				-->
			</div>
			<div class="modal-footer">
			</div>
		</div>
	</div>
</div>