<div class="row">
	<div class="col-lg-12">
		<h1 class="page-header">Терористюшки</h1>
		<div class="table-responsive">
			<table class="table table-bordered list-of-albums">
				<tr>
					<td>ID</td>
					<td>Name</td>
					<td>Edit</td>
					<td>Delete</td>
				</tr>
				<?php foreach($this->params["terroristsPending"] as $value):?>
					<tr>
						<td><?php echo $value["id"]?></td>
						<td><?php echo $value["name"]?></td>
						<td><a href = "/album/edit/<?php echo $value["id"]?>"><i class="fa fa-edit"></i></a> <i data-id = "<?php echo $value["id"]?>" class="fa fa-plus save-terrorist"></i></td>
						<td><?php if($this->params["indentityRole"] == "admin"):?><i data-id = "<?php echo $value["id"]?>" class="fa fa-trash-o drop-terrorist"></i><?php endif;?></td>
					</tr>
				<?php endforeach;?>
				<tr>
					<td>***</td>
					<td>***</td>
					<td>***</td>
					<td>***</td>
				</tr>
				<?php foreach($this->params["terroristsActive"] as $value):?>
					<tr>
						<td><?php echo $value["id"]?></td>
						<td><?php echo $value["name"]?></td>
						<td><a href = "/album/edit/<?php echo $value["id"]?>"><i class="fa fa-edit"></i></a></td>
						<td><?php if($this->params["indentityRole"] == "admin"):?><i data-id = "<?php echo $value["id"]?>" class="fa fa-trash-o drop-terrorist"></i><?php endif;?></td>
					</tr>
				<?php endforeach;?>
			</table>
		</div>
	</div>
</div>